"""Add index to User.auth_token

Revision ID: 1f9b411bf6df
Revises: 309634f4580b
Create Date: 2015-10-28 14:27:43.368014

"""

# revision identifiers, used by Alembic.
revision = '1f9b411bf6df'
down_revision = '309634f4580b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_auth_token'), 'users', ['auth_token'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_token'), table_name='users')
    ### end Alembic commands ###
