"""Add auth_token to User

Revision ID: 309634f4580b
Revises: 198b0eebcf9
Create Date: 2015-10-27 14:24:54.304696

"""

# revision identifiers, used by Alembic.
revision = '309634f4580b'
down_revision = '198b0eebcf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_token')
    ### end Alembic commands ###
