"""Add context field to LogEventType

Revision ID: 312f53da77dd
Revises: 578c1486eed2
Create Date: 2015-10-31 18:06:48.526870

"""

# revision identifiers, used by Alembic.
revision = '312f53da77dd'
down_revision = '578c1486eed2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_event_types', sa.Column('context', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_event_types', 'context')
    ### end Alembic commands ###
